language: scala
sudo: required
addons:
  - postgresql: "9.3"
services:
  - postgresql
before_script:
  - ./scripts/create_test_db
scala:
  - 2.11.7
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
env:
  global:
    JAVA_OPTS=-Xmx2g
    SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:MaxPermSize=512m"
install:
  - gem install sass
script:
  - sbt 'publishAll'
  - git clone https://github.com/scala-exercises/exercises-stdlib.git stdlib; pushd stdlib; sbt publishLocal; popd
  - git clone https://github.com/scala-exercises/exercises-cats.git cats; pushd cats; sbt publishLocal; popd
  - git clone https://github.com/scala-exercises/exercises-shapeless.git shapeless; pushd shapeless; sbt publishLocal; popd
  - sbt 'server/test'
  - sbt 'client/test'
  - sbt 'definitions/test'
  - sbt 'runtime/test'
  - sbt 'compiler/test'
