language: scala
sudo: required
addons:
  - postgresql: "9.3"
services:
  - postgresql
before_script:
  - ./scripts/create_test_db
scala:
  - 2.11.7
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
env:
  global:
    JAVA_OPTS=-Xmx2g
    SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:MaxPermSize=512m"
install:
  - gem install sass
script:
  - pushd core && sbt 'test' && popd
  - pushd site && sbt 'project server' 'test' && popd
  - pushd site && sbt 'project client' 'test' && popd
  - pushd site && sbt 'project content' 'test' && popd
