language: scala
scala:
   - 2.11.7
jdk:
  - oraclejdk8
before_install:
  - pip install --user codecov
install:
  - gem install sass
script:
  - cd site/
  - sbt ++$TRAVIS_SCALA_VERSION compile
after_success:
  - codecov